# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: influxdb-router
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
dockers:
  - 
    image: samitpal/influxdb-router
    goos: linux
    goarch: amd64
    binary: influxdb-router
  
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
